apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-udp-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
  - port: 53
    protocol: UDP
