# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  tag: v0.1.3

service:
  type: NodePort
  port: 80
  targetPort: 8079
  NodePort: 30001
