apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    #certmanager.k8s.io/acme-challenge-type: http01
    #certmanager.k8s.io/cluster-issuer: letsencrypt-production
    #ingress.kubernetes.io/proxy-body-size: "0"
    #ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    #kubernetes.io/tls-acme: "true"
    #nginx.ingress.kubernetes.io/proxy-body-size: "0"
    #nginx.ingress.kubernetes.io/ssl-redirect: "true"
  labels:
    app: frontend
  name: frontend
spec:
  rules:
  - host: shop.35.228.138.157.nip.io
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: {{ .Values.service.port }}
        #path: /
  #tls:
  #- hosts:
    #- shop.35.228.138.157.nip.io
    #secretName: shop.35.228.138.157.nip.io
