apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: kshuleshov/otus-kuber-2020-04_kubernetes-intro_hipster-frontend
    name: frontend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
