apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: web
    image: kshuleshov/otus-kuber-2020-04_kubernetes-intro_web
    livenessProbe:
      tcpSocket:
        port: 8000
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
    volumeMounts:
    - name: app
      mountPath: /app
  initContainers:
  - name: init
    image: alpine
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}
